OnlineFoodWebsite/Areas/Administrator/Controllers/NHANVIENController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFoodWebsite.Model;

namespace OnlineFoodWebsite.Areas.Administrator.Controllers
{
    public class NHANVIENController : Controller
    {
        private OnlineFoodWebsiteDbContext db = new OnlineFoodWebsiteDbContext();
        private static Random random = new Random();
        // GET: Administrator/NHANVIENsontroller
        public ActionResult Index()
        {
            if (TempData["result5"] != null)
            {
                ViewBag.Message5 = TempData["result5"].ToString();
            }
            if (TempData["result6"] != null)
            {
                ViewBag.Message6 = TempData["result6"].ToString();
            }
            if (TempData["result7"] != null)
            {
                ViewBag.Message7 = TempData["result7"].ToString();
            }
            return View(db.NHANVIENs.ToList());
        }

        // GET: Administrator/NHANVIENsontroller/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // GET: Administrator/NHANVIENsontroller/Create
        public ActionResult Create()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem()
            {
                Text = "Quản lý",
                Value="Quản lý"
            }) ;
            list.Add(new SelectListItem()
            {
                Text = "Nhân viên bếp",
                Value = "Nhân viên bếp"
            });
            list.Add(new SelectListItem()
            {
                Text = "Nhân viên kho",
                Value = "Nhân viên kho"
            });
            list.Add(new SelectListItem()
            {
                Text = "Nhân viên đơn hàng",
                Value = "Nhân viên đơn hàng"
            });
            ViewBag.ListChucVu = new SelectList(list, "Value", "Text");
            return View();
        }

        // POST: Administrator/NHANVIENsontroller/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TENNV,NGAYSINH,SDT,CHUCVU,TAIKHOAN,MATKHAU")] NHANVIEN nHANVIEN, HttpPostedFileBase file)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem()
            {
                Text = "Quản lý",
                Value = "Quản lý"
            });
            list.Add(new SelectListItem()
            {
                Text = "Nhân viên bếp",
                Value = "Nhân viên bếp"
            });
            list.Add(new SelectListItem()
            {
                Text = "Nhân viên kho",
                Value = "Nhân viên kho"
            });
            list.Add(new SelectListItem()
            {
                Text = "Nhân viên đơn hàng",
                Value = "Nhân viên đơn hàng"
            });
            ViewBag.ListChucVu = new SelectList(list, "Value", "Text");
            if (file != null)
            {

                string ImageName = System.IO.Path.GetFileName(file.FileName);
                string physicalPath = Server.MapPath("~/Areas/Administrator/Content/images/" + ImageName);

                // save image in folder
                file.SaveAs(physicalPath);

                if (ModelState.IsValid)
                {
                    string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
                    nHANVIEN.MANV = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds().ToString();
                    nHANVIEN.HINHANH = ImageName;
                    db.NHANVIENs.Add(nHANVIEN);
                    db.SaveChanges();
                    TempData["result5"] = "Them moi nhan vien thanh cong!";
                    return RedirectToAction("Index");

                }

            }

            
            return View();
        }

        // GET: Administrator/NHANVIENsontroller/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // POST: Administrator/NHANVIENsontroller/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id,[Bind(Include = "TENNV,TAIKHOAN,NGAYSINH,SDT,MATKHAU,CHUCVU")] NHANVIEN nHANVIEN, HttpPostedFileBase file)
        {
            NHANVIEN nv = db.NHANVIENs.Find(id);
            if (file != null)
            {

                string ImageName = System.IO.Path.GetFileName(file.FileName);
                string physicalPath = Server.MapPath("~/Areas/Administrator/Content/images/" + ImageName);

                // save image in folder
                file.SaveAs(physicalPath);
                if (ModelState.IsValid)
                {
                    nv.TENNV = nHANVIEN.TENNV;
                    nv.TAIKHOAN = nHANVIEN.TAIKHOAN;
                    nv.MATKHAU = nHANVIEN.MATKHAU;
                    nv.NGAYSINH = nHANVIEN.NGAYSINH;
                    nv.SDT = nHANVIEN.SDT;
                    nv.CHUCVU = nHANVIEN.CHUCVU;
                    nv.HINHANH = ImageName;
                    db.Entry(nv).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["result6"] = "Cap nhat thanh cong nhan vien!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    nv.TENNV = nHANVIEN.TENNV;
                    nv.TAIKHOAN = nHANVIEN.TAIKHOAN;
                    nv.MATKHAU = nHANVIEN.MATKHAU;
                    nv.NGAYSINH = nHANVIEN.NGAYSINH;
                    nv.SDT = nHANVIEN.SDT;
                    nv.CHUCVU = nHANVIEN.CHUCVU;
                    db.Entry(nv).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["result6"] = "Cap nhat thanh cong nhan vien!";
                    return RedirectToAction("Index");
                }
            }
           
            return View(nv);
        }

        // GET: Administrator/NHANVIENsontroller/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // POST: Administrator/NHANVIENsontroller/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            db.NHANVIENs.Remove(nHANVIEN);
            db.SaveChanges();
            TempData["result7"] = "Xoa nhan vien thanh cong!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
       
    }
}

OnlineFoodWebsite/Areas/Administrator/Views/NHANVIEN/Create.cshtml
@model OnlineFoodWebsite.Model.NHANVIEN

@{
    ViewBag.Title = "Create";
}

<h2>Thêm mới nhân viên</h2>

@using (Html.BeginForm("Create", "NHANVIEN", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.Label("Tên nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TENNV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENNV, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("SĐT", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.CHUCVU, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.DropDownListFor(model => model.CHUCVU, ViewBag.ListChucVu as SelectList, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CHUCVU, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Tài khoản đăng nhập", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TAIKHOAN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TAIKHOAN, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Mật khẩu đăng nhập", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MATKHAU, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MATKHAU, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Hình minh họa", new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            <input type="file" name="file" id="file" style="width: 100%;" />
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineFoodWebsite/Areas/Administrator/Views/NHANVIEN/Delete.cshtml
@model OnlineFoodWebsite.Model.NHANVIEN

@{
    ViewBag.Title = "Delete";
}

<h2>Xóa nhân viên</h2>

<h3>Bạn muốn xóa nhân viên này?</h3>
<div>
    <h4>@Model.TENNV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MANV)
        </dd>
        <br />
        <dt>
            Tên nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNV)
        </dd>
        <br />
        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NGAYSINH)
        </dd>
        <br />
        <dt>
            SĐT
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>
        <br />
        <dt>
            Chức vụ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CHUCVU)
        </dd>
        <br />
        <dt>
            Tài khoản đăng nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TAIKHOAN)
        </dd>
        <br />
        <dt>
            Mật khẩu đăng nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATKHAU)
        </dd>
        <br />
        <dt>
            Hoạt động gần nhất
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LASTACTIVE)
        </dd>
        <br />
        <dt>
            Hình minh họa
        </dt>

        <dd>
            <img src="~/Areas/Administrator/Content/images/@Url.Content(Model.HINHANH)" alt="Image" width="128" height="128" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineFoodWebsite/Areas/Administrator/Views/NHANVIEN/Details.cshtml
@model OnlineFoodWebsite.Model.NHANVIEN

@{
    ViewBag.Title = "Details";
}

<h2>Thông tin nhân viên</h2>

<div>
    <h4>@Model.TENNV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MANV)
        </dd>
        <br />
        <dt>
            Tên nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNV)
        </dd>
        <br />
        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NGAYSINH)
        </dd>
        <br />
        <dt>
            SĐT
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>
        <br />
        <dt>
            Chức vụ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CHUCVU)
        </dd>
        <br />
        <dt>
            Tài khoản đăng nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TAIKHOAN)
        </dd>
        <br />
        <dt>
            Mật khẩu đăng nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATKHAU)
        </dd>
        <br />
        <dt>
            Hoạt động gần nhất
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LASTACTIVE)
        </dd>
        <br />
        <dt>
            Hình minh họa
        </dt>

        <dd>
            <img src="~/Areas/Administrator/Content/images/@Url.Content(Model.HINHANH)" alt="Image" width="128" height="128" />
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MANV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineFoodWebsite/Areas/Administrator/Views/NHANVIEN/Edit.cshtml
@model OnlineFoodWebsite.Model.NHANVIEN

@{
    ViewBag.Title = "Edit";
}

<h2>Sửa thông tin nhân viên</h2>

@using (Html.BeginForm("Edit", "NHANVIEN", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>@Model.TENNV</h4>
        <div class="form-group">
            @Html.Label("Tên nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("SĐT", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CHUCVU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CHUCVU, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Tài khoản đăng nhập", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TAIKHOAN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TAIKHOAN, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Mật khẩu đăng nhập", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATKHAU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MATKHAU, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Hình minh họa", new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                <input type="file" name="file" id="file" style="width: 100%;" />
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

OnlineFoodWebsite/Areas/Administrator/Views/NHANVIEN/Index.cshtml
@model IEnumerable<OnlineFoodWebsite.Model.NHANVIEN>

@{
    ViewBag.Title = "Index";
}
@if (ViewBag.Message5 != null)
{
    <script>
    var text='@ViewBag.Message5';
    window.alert(text);
    </script>
}
@if (ViewBag.Message6 != null)
{
    <script>
    var text='@ViewBag.Message6';
    window.alert(text);
    </script>
}
@if (ViewBag.Message7 != null)
{
    <script>
    var text='@ViewBag.Message7';
    window.alert(text);
    </script>
}
<h2>Danh sách nhân viên hệ thống</h2>
<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Nhập tên cần tìm" title="Type in a name">
<br />
<br />

<table class="table" id="myTable">
    <tr>
        <th>STT</th>
        <th>
            Mã nhân viên
        </th>
        <th>
            Tên nhân viên
        </th>
        <th>
            Ngày sinh
        </th>
        <th>
            SĐT
        </th>
        <th>
            Chức vụ
        </th>
        <th>Hoạt động gần nhất</th>
    </tr>

    @{
        int i = 0;
        foreach (var item in Model)
        {
            i++;
            <tr>
                <td>@i</td>
                <td>
                    @Html.DisplayFor(modelItem => item.MANV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TENNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NGAYSINH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CHUCVU)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LASTACTIVE)
                </td>
                @{ if (((string)Session["role"]) == "Quản lý")
                    {
                        <td>
                            @Html.ActionLink("Sửa", "Edit", new { id = item.MANV }) |
                            @Html.ActionLink("Chi tiết", "Details", new { id = item.MANV }) |
                            @Html.ActionLink("Xóa", "Delete", new { id = item.MANV })
                        </td>
                    }
                    else
                    {

                    }
                }

            </tr>
        }
    }
</table>

@{ if (((string)Session["role"]) == "Quản lý")
    {
        <p>
            @Html.ActionLink("Thêm mới", "Create")
        </p>
    }
}
<script>
    function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[2];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>